name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: ./.github/vars/global.env

      - name: Setup NodeJS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Application Code
        run: npm run lint

      - name: Build Application Code
        env:
          REACT_APP_API_URL: 'http://localhost:3001/api'
        run: |
          echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env.production.local
          npm run build

      - name: Test Application Code
        run: npm run test

      - name: Deploy Application Code
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
